spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: easy
    password: easy
  liquibase:
    change-log: classpath:liquibase-changeLog.xml
    user: easy
    password: easy

app:
  kafka:
    payment-topic: easy.payment
  path:
    transactions: #todo ??????? ????
